/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/piso.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials["Material.001"]}
        position={[-1, -5, -15]}
        rotation={[Math.PI / 3, 0, 0]}
        scale={[1.59*15, 1*15, 1*15]}
      />
    </group>
  );
}

useGLTF.preload("/piso.glb");

